linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - revive
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/ZetNetwork/Users