services:
#  app:
#    container_name: bot
#    build: .
#    environment:
#      - PG_DSN=${PG_DSN}
#      - PG_DRIVER=${PG_DRIVER}
#      - IAM_TOKEN=${IAM_TOKEN}
#      - YANDEX_GROUP=${YANDEX_GROUP}
#      - BOT_TOKEN=${BOT_TOKEN}
#    networks:
#      - app_network
#    depends_on:
#      - db


  db:
    container_name: appDatabase
    image: postgres:alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  data:

networks:
  app_network:
    driver: bridge