name: Users Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Run Tests
        run: go test ./...